import { cookies } from 'next/headers';

import { getLiveFeedonServer } from '@/services/feed';
import Feed from '@/containers/feed';

const FeedPage = async () => {
  const cookieStore = cookies();
  const refreshToken = cookieStore.get('refreshToken')?.value;
  // const data = await getLiveFeed(-1, refreshToken);
  const data = {
    content: [
      {
        memberId: 1,
        actionId: 18,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '대학은 어디 갈거니?',
        action: '왜잉래래래랠래5',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-02-01 13:03:18',
      },
      {
        memberId: 1,
        actionId: 17,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '그 대학 간 거 만족하니?',
        action: '왜잉래래래랠래5',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-02-01 13:03:14',
      },
      {
        memberId: 1,
        actionId: 16,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '이번 모의고사 몇 등급이니?',
        action: '왜잉래래래랠래5',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-02-01 13:02:51',
      },
      {
        memberId: 2,
        actionId: 15,
        nickname: 'fauy0438',
        profileImage: 8,
        nag: '이번 모의고사 몇 등급이니?',
        action: '왜잉래래래랠래5',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: false,
        isFavorite: false,
        createdAt: '2024-01-30 12:07:57',
      },
      {
        memberId: 2,
        actionId: 14,
        nickname: 'fauy0438',
        profileImage: 8,
        nag: '이번 모의고사 몇 등급이니?',
        action: '왜잉래래래랠래4',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: false,
        isFavorite: false,
        createdAt: '2024-01-30 12:07:54',
      },
      {
        memberId: 2,
        actionId: 13,
        nickname: 'fauy0438',
        profileImage: 8,
        nag: '이번 모의고사 몇 등급이니?',
        action: '왜잉래래래랠래3',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: false,
        isFavorite: false,
        createdAt: '2024-01-30 12:07:51',
      },
      {
        memberId: 2,
        actionId: 12,
        nickname: 'fauy0438',
        profileImage: 8,
        nag: '이번 모의고사 몇 등급이니?',
        action: '왜잉래래래랠래2',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: false,
        isFavorite: false,
        createdAt: '2024-01-30 12:07:49',
      },
      {
        memberId: 2,
        actionId: 11,
        nickname: 'fauy0438',
        profileImage: 8,
        nag: '이번 모의고사 몇 등급이니?',
        action: '왜잉래래래랠래',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: false,
        isFavorite: false,
        createdAt: '2024-01-30 12:07:46',
      },
      {
        memberId: 2,
        actionId: 10,
        nickname: 'fauy0438',
        profileImage: 8,
        nag: '이번 모의고사 몇 등급이니?',
        action: '잔소리는 그만~~~!5',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: false,
        isFavorite: false,
        createdAt: '2024-01-30 12:07:37',
      },
      {
        memberId: 1,
        actionId: 9,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '이번 모의고사 몇 등급이니?',
        action: '잔소리는 그만~~~!5',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-01-30 12:06:23',
      },
      {
        memberId: 1,
        actionId: 8,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '이번 모의고사 몇 등급이니?',
        action: '잔소리는 그만~~~!3333',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-01-30 12:06:19',
      },
      {
        memberId: 1,
        actionId: 7,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '언제까지 그렇게 놀거니?',
        action: '잔소리는 그만~~~!3333',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-01-30 12:06:14',
      },
      {
        memberId: 1,
        actionId: 6,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '언제까지 그렇게 놀거니?',
        action: '잔소리는 그만~~~!222',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-01-30 12:06:11',
      },
      {
        memberId: 1,
        actionId: 5,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '언제까지 그렇게 놀거니?',
        action: '잔소리는 그만~~~!',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-01-30 12:06:05',
      },
      {
        memberId: 1,
        actionId: 4,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '언제까지 그렇게 놀거니?',
        action: '앞으로 열심히 하겠습니다.4',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-01-30 11:51:43',
      },
      {
        memberId: 1,
        actionId: 3,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '언제까지 그렇게 놀거니?',
        action: '앞으로 열심히 하겠습니다.4',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 1,
        isFollow: null,
        isFavorite: true,
        createdAt: '2024-01-30 11:51:42',
      },
      {
        memberId: 1,
        actionId: 2,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '언제까지 그렇게 놀거니?',
        action: '앞으로 열심히 하겠습니다.4',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-01-30 11:51:41',
      },
      {
        memberId: 1,
        actionId: 1,
        nickname: 'prpt9296',
        profileImage: 7,
        nag: '언제까지 그렇게 놀거니?',
        action: '앞으로 열심히 하겠습니다.4',
        categoryId: 1,
        categoryTitle: '학업/진로',
        favoriteCount: 0,
        isFollow: null,
        isFavorite: false,
        createdAt: '2024-01-30 11:51:40',
      },
    ],
    pageable: {
      pageNumber: 0,
      pageSize: 20,
      sort: {
        empty: true,
        sorted: false,
        unsorted: true,
      },
      offset: 0,
      paged: true,
      unpaged: false,
    },
    sort: {
      empty: true,
      sorted: false,
      unsorted: true,
    },
    numberOfElements: 18,
    number: 0,
    first: true,
    last: true,
    size: 20,
    empty: false,
  };

  return <Feed {...data} />;
};

export default FeedPage;
